# Generated by Django 6.0.4 on 2026-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member")],
                default="admin",
                max_length=10,
            ),
        ),
    ]
